from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

import datetime


def generate_pdf(
    recommendation,
    ticket,
    similar_incidents,
    response_time,
    filename="SAP_AI_Recommendation_Reports.pdf"
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    body = styles["BodyText"]

    story = []

    # =====================================================
    # HEADER
    # =====================================================

    story.append(
        Paragraph(
            "<font size=22><b>SAP MDG Intelligent Support Assistant</b></font>",
            title
        )
    )

    story.append(
        Paragraph(
            "<font size=15><b>Enterprise AI Recommendation Report</b></font>",
            heading
        )
    )

    story.append(
        Paragraph(
            "Master Thesis Project | IU International University",
            body
        )
    )

    story.append(
        Paragraph(
            "Artificial Intelligence powered SAP Support Recommendation using Retrieval-Augmented Generation (RAG)",
            body
        )
    )

    story.append(Spacer(1,0.25*inch))

    story.append(
        Paragraph(
            "<b>Executive Summary</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            f"""
This report was automatically generated by the SAP MDG Intelligent Support Assistant.

The submitted SAP support ticket was analyzed using Sentence Transformers,
FAISS semantic retrieval and the Llama 3.2 Large Language Model.

The recommendation is generated from historical SAP incident knowledge.
""",
            body
        )
    )

    story.append(Spacer(1,0.3*inch))

    # =====================================================
    # SUBMITTED TICKET
    # =====================================================

    story.append(
        Paragraph(
            "<b>Submitted Ticket</b>",
            heading
        )
    )

    story.append(
        Paragraph(ticket, body)
    )

    story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph(
            "<b>AI Analysis Overview</b>",
            heading
        )
    )

    overview = [
        ["Confidence", f"{recommendation['confidence']}%"],
        ["Confidence Level", recommendation["confidence_level"]],
        ["Embedding", "all-MiniLM-L6-v2"],
        ["Vector Database", "FAISS"],
        ["LLM", "Llama 3.2"],
        ["Retrieved Records", len(similar_incidents)],
        ["Response Time", f"{response_time} sec"]
    ]

    table = Table(overview, colWidths=[180, 250])

    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#DCEEFF")),
        ("BACKGROUND", (1, 0), (1, -1), colors.white),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8)
    ]))

    story.append(table)

    story.append(Spacer(1, 0.3 * inch))

    # =====================================================
    # ISSUE SUMMARY
    # =====================================================

    story.append(
        Paragraph(
            "<b>Issue Summary</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            recommendation.get("issue_summary", ""),
            body
        )
    )

    story.append(Spacer(1, 0.20 * inch))

    # =====================================================
    # ROOT CAUSE
    # =====================================================

    story.append(
        Paragraph(
            "<b>Possible Root Causes</b>",
            heading
        )
    )

    for item in recommendation.get("root_cause", []):

        story.append(
            Paragraph(f"• {item}", body)
        )

    story.append(Spacer(1, 0.20 * inch))

    # =====================================================
    # DIAGNOSTIC STEPS
    # =====================================================

    story.append(
        Paragraph(
            "<b>Diagnostic Steps</b>",
            heading
        )
    )

    for i, item in enumerate(
        recommendation.get("diagnostic_steps", []),
        start=1
    ):

        story.append(
            Paragraph(
                f"{i}. {item}",
                body
            )
        )

    story.append(Spacer(1, 0.20 * inch))

    # =====================================================
    # RECOMMENDED RESOLUTION
    # =====================================================

    story.append(
        Paragraph(
            "<b>Recommended Resolution</b>",
            heading
        )
    )

    for i, item in enumerate(
        recommendation.get("recommended_resolution", []),
        start=1
    ):

        story.append(
            Paragraph(
                f"{i}. {item}",
                body
            )
        )

    story.append(Spacer(1, 0.30 * inch))

    # =====================================================
    # AI ANALYSIS TABLE
    # =====================================================

    story.append(
        Paragraph(
            "<b>AI Analysis</b>",
            heading
        )
    )

    analysis_table = [

        ["Confidence", f"{recommendation.get('confidence',0)}%"],

        ["Confidence Level", recommendation.get("confidence_level","")],

        ["Embedding Model", "all-MiniLM-L6-v2"],

        ["Vector Database", "FAISS"],

        ["LLM", "Llama 3.2"],

        ["Response Time", f"{response_time} sec"]

    ]

    table = Table(
        analysis_table,
        colWidths=[180,250]
    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.lightblue),

            ("GRID",(0,0),(-1,-1),1,colors.grey),

            ("BACKGROUND",(0,0),(0,-1),colors.whitesmoke),

            ("FONTNAME",(0,0),(-1,-1),"Helvetica"),

            ("BOTTOMPADDING",(0,0),(-1,-1),8)

        ])

    )

    story.append(table)

    story.append(Spacer(1, 0.30 * inch))

    # =====================================================
    # SIMILAR INCIDENTS
    # =====================================================

    story.append(
        Paragraph(
            "<b>Knowledge Base Evidence</b>",
            heading
        )
    )

    similar_table = [["Issue","Business Object","Module","Similarity"]]

    for incident in similar_incidents:

        similar_table.append([

            incident["issue"],

            incident["business_object"],

            incident["module"],

            f'{incident["similarity"]}%'

        ])

    table = Table(similar_table)

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.black),

            ("BACKGROUND",(0,1),(-1,-1),colors.beige),

            ("BOTTOMPADDING",(0,0),(-1,0),10)

        ])

    )

    story.append(table)

    story.append(Spacer(1,0.35*inch))

    # =====================================================
    # FOOTER
    # =====================================================

    story.append(Spacer(1, 0.4 * inch))

    story.append(
        Paragraph(
            "<b>Generated by SAP MDG Intelligent Support Assistant</b>",
            heading
        )
    )

    story.append(
        Paragraph(
            "IU International University",
            body
        )
    )

    story.append(
        Paragraph(
            "Master Thesis - MSc Artificial Intelligence",
            body
        )
    )

    story.append(
        Paragraph(
            "Developer: Mohammad Aryaan",
            body
        )
    )

    story.append(
        Paragraph(
            "Year: 2026",
            body
        )
    )

    doc.build(story)

    return filename